version: '3'
services:
  filebeat-docker-monitoring:
    image: docker.elastic.co/beats/filebeat:7.17.0
    container_name: filebeat-docker-monitoring
    restart: unless-stopped
    user: root
    volumes:
      - ./docker-compose.filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
